#!/usr/bin/env bash

# --- BASH SETUP --- #
alias ls='eza -a1 --group-directories-first --icons'
alias ll='ls -al'
alias l='ls'

alias c='clear'
alias cc='clear; echo -e "\033c\e[3J"'

alias printpath="echo $PATH | tr : '\n'"

alias rbash='source ~/.zshrc'

# --- BASH SETUP --- #
alias kadevcfg='cd ~/projects/kadevrc && vim'
alias kubecfg='vim ~/.kube/config'
alias ghosttycfg='vim ~/.config/ghostty/config'
alias tmuxcfg='vim ~/.tmux.conf'

alias ytm4a='yt-dlp -f "bestaudio[ext=m4a]" -o "%(title)s.%(ext)s"'
alias ytfull='yt-dlp -f "bv+ba/best" -o "%(title)s.%(ext)s"'

alias home='cd ~ && zellij action rename-tab HOME'
