#!/usr/bin/env bash
# --- GIT SETUP / PROJECT SHORTCUTS ---- #
function parse_git_branch() {
  git branch 2>/dev/null | sed -n -e 's/^\* \(.*\)/[\1]/p'
}

function parse_branch_raw() {
  git branch 2>/dev/null | sed -n -e 's/^\* \(.*\)/\1/p'
}

COLOR_DEF=$'%f'
COLOR_DIR=$'%F{#ef9f76}'
COLOR_GIT=$'%F{#a6d189}'
setopt PROMPT_SUBST
export PROMPT='${COLOR_DIR}%~ ${COLOR_GIT}$(parse_git_branch)${COLOR_DEF} $ '

# this is very important to enable commit signing using GPG keys
export GPG_TTY=$(tty)
# export PS1='\[\033[01;32m\]\W\[\033[00m\]$(parse_branch) $ '

alias b='git branch'
alias s='git status'
alias diff='git diff'
alias add='git add -A'
alias glog='git log --show-signature'
alias reset-hard='git reset --hard'
alias fetch='git fetch --all'
alias cout='git checkout'
alias cout-b='git checkout -b'
alias commit='git commit -v'
alias gresign="git rebase --exec 'git commit --amend --no-edit -n -S' -i"

pull() {
  if [ -z "$1" ]; then
    git pull origin "$(parse_branch_raw)"
  else
    git pull origin "$1"
  fi
}

push() {
  git push origin $(parse_branch_raw)
}
