#!/usr/bin/env bash

export PATH="$PATH:$HOME/projects/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:/usr/local/go/bin"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export PATH="$HOME/.local/share/nvim/mason/packages/jdtls:$PATH"
export PATH="$HOME/.local/share/intellij/bin:$PATH"
export PATH="$HOME/.local/share/kotlin_lsp/bin:$PATH"
export PATH="$HOME/.local/share/nvim/lsp_servers/jdtls/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

export PSQL_EDITOR=$(which nvim)
export EDITOR='nvim'
export VISUAL='nvim'
