#!/usr/bin/env bash
if [[ $TERM == xterm ]]; then TERM=xterm-256color; fi

DEFAULT_SESSION_NAME=kadev

alias tmux-rw='tmux rename-window'
alias rw='tmux-rw'

alias rtmux='tmux source-file ~/.tmux.conf'

function tmux-w() {
  if [ ! -z "$1" ]; then
    TITLE="$1"
  else
    echo "usage: tmux-w window_name [command]"
    return 1
  fi

  tmux new-window -dn $1

  if [ ! -z "$2" ]; then
    tmux send-keys -t "$DEFAULT_SESSION_NAME:$TITLE" "$2" "C-m"
  fi
}

alias tmux-work-setup='tmux-rw proj:1 &&\
  tmux-w proj:2 &&\
  tmux-w databases &&\
  tmux-w cli &&\
  clear &&\
  tmux select-window -t 1'

alias tmux-ns="tmux new-session -ds $DEFAULT_SESSION_NAME &&\
  sleep 1 && tmux send-keys -t $DEFAULT_SESSION_NAME:1 tmux-work-setup C-m &&\
  tmux a"

alias tmux-k='tmux kill-server'

function tmux-cmd() {
  tmux send-keys -t "$DEFAULT_SESSION_NAME:$1" "$2" "C-m"
}

function tmux-sigterm() {
  tmux send-keys -t "$DEFAULT_SESSION_NAME:$1" "C-c"
}
