# shell awareness
set-option -g default-command $SHELL

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'

run '~/.tmux/plugins/tpm/tpm'

# escape-time fix for nvim esc delay issue
set -s escape-time 0

# windows start from 1 instead of 0
set -g base-index 1
set -g pane-base-index 1

# unbind no longer used keybinds
unbind-key -n C-l
unbind-key -n C-h
unbind-key -n C-up
unbind-key -n C-down
unbind-key -n C-left
unbind-key -n C-right
unbind-key -n C-z

# vim like copy paste
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection

# window navigation
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5

bind-key -n M-6 select-window -t 1
bind-key -n M-7 select-window -t 2
bind-key -n M-8 select-window -t 3
bind-key -n M-9 select-window -t 4
bind-key -n M-0 select-window -t 5

# support window navigation in vi mode
bind-key -T copy-mode -n M-1 select-window -t 1
bind-key -T copy-mode -n M-2 select-window -t 2
bind-key -T copy-mode -n M-3 select-window -t 3
bind-key -T copy-mode -n M-4 select-window -t 4
bind-key -T copy-mode -n M-5 select-window -t 5

bind-key -T copy-mode -n M-7 select-window -t 2
bind-key -T copy-mode -n M-8 select-window -t 3
bind-key -T copy-mode -n M-9 select-window -t 4
bind-key -T copy-mode -n M-0 select-window -t 5
bind-key -T copy-mode -n M-0 select-window -t 5

# pane utilities
bind -n C-j select-pane -t:.+
bind -n C-k select-pane -t:.+
bind -n C-f resize-pane -Z

set-window-option -g window-status-current-style bg="#89B4FA",fg="black"

set -g status-bg black
set -g status-fg white

# vim colors inconsistency fix
set -g terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "screen-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'

# pane management
bind-key "\"" split-window -v -c "#{pane_current_path}"
bind-key "%" split-window -h -c "#{pane_current_path}"

bind-key -n M-up resize-pane -U 5
bind-key -n M-down resize-pane -D 5

set -g set-clipboard on
set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"
